### PR TITLE
Add canvas rotation using NumPad + KeyPad numbers

### PR DESCRIPTION
**Pull request by larpon**
* Add Qt::KeypadModifier to known modifier keys
* Add Rotate Canvas (Anti) Clockwise key bindings
* Start of WIP showing Key Bindings in tool tips

### CODE REVIEW

**Comment by larpon** [comment]
@herace are issues unavailable on forks?

**Comment by Jose-Moreno** [comment]
@Larpon They shouldn't be, possible @herace has to enable permissions so other github members can submit issues as seen on this stackoverflow answer: https://softwareengineering.stackexchange.com/questions/179468/forking-a-repo-on-github-but-allowing-new-issues-on-the-fork

**Comment by larpon** [comment]
Ah thanks for clarifying @Jose-Moreno

**Comment by herace** [comment]
Hey @Larpon sorry for the long wait, wow honestly wasn't expecting contributors so soon. Going to take a look at this :+1:

**Comment by larpon** [comment]
Hey @herace - no worries :) I can't promise a steady pace anyway. I thought I'd just start with getting to know some internals :)

**Comment by larpon** [comment]
The tool tip showing is a bit crude and should probably be wrapped somehow.

**Comment by herace** [comment]
Hey @Larpon just complied and i personally found theses canvas rotate hotkeys very useful, good stuff. Also dont worry how crude it is, as long it improve the overall user experience :+1:.  

Also I think focusing on adding shortcuts will definitely be a big major step improving this application.

Forgot to mention it but good work on getting rid of those compile warnings, its nice to compile something without the constant background noise.  Good stuff :+1: 

And lastly dont worry about keeping up a constant stream of commits, go at your own pace :)  :ok_hand:

**Comment by larpon** [comment]
@herace - awesome! Thanks for taking your time. I'll probably work a little more on adding some tool tips :)

**Pull request merged**
