### PR TITLE
Add option to move canvas with middle-mouse button

### PR DESCRIPTION
**Pull request by larpon**
I find this particular feature very intuitive with other software I have worked with. I.e: Krita, Inkscape, The GIMP + many more.

### CODE REVIEW

**Comment by larpon** [comment]
... squashed with a bugfix

**Comment by herace** [comment]
Ohhh wow, funny thing you brought this up. <strike>One i first things i notice using AnimeEffects is that how tedious it is not able to move the canvas without some kind of hotkey </strike> . Middle mouse is one of the hotkeys i use to move the canvas, but when im using my screen table i use spacebar 100% of the time (Like in Krita, Photoshop, etc.).

EDIT: Sorry, spacebar was already the move canvas default hotkey. The hotkey i wanted at the time was the middle mouse button after all 

Going to QA this.

**Comment by herace** [comment]
hrrmm.... weird. Tried to use the middle mouse button to move the canvas but wasn't able to. I did a clean git clone -b but wasn't working :thinking: 
ss_git

**Comment by larpon** [comment]
Have you enabled it in the General settings?
I made it so it's off by default

**Comment by herace** [comment]
okay cool, tested it and it feels really nice, great feature :+1: 
merging now

**Pull request merged**
