### PR TITLE
Add theme support

### PR DESCRIPTION
**Pull request by larpon**
This PR will add theme support including support for customizations and tweaks.

**Features**
* Theme can be changed at runtime
* Easy to add more themes, via QWidgets stylesheet support
* Kept original "classic" theme as default
* Added a default theme that correctly uses system theme
* Added support for auto detecting icon color in default (system) theme

### CODE REVIEW

**Comment by larpon** [comment]
@herace - you should probably squash this into one commit. In case we want to roll things back at some point?

**Comment by herace** [comment]
oh wow, excellent work @Larpon, Im going to Peer review this :+1:

**Comment by herace** [comment]
Cool, its really nice to have to themes on AE. Great stuff man :+1:

**Comment by larpon** [comment]
Awesome! There's still room for improvement, but it's a start. We could also provide a custom dark theme maybe (so you don't have to have a dark system theme to get a dark AE theme)

**Comment by herace** [comment]
Yeah, since now the foundation is established putting themes will be less a hassle and of course later on there will be a dark theme. This merge is definitely good stuff :+1:

**Pull request merged**
