### PR TITLE
Add feature timeline information

### LINKED ISSUE #7: [Feature Request] Show frame number / Timeline scales
Hi,
I'm experimenting with having a current frame showed somewhere in the UI in addition to the time scale indication which is based on `fps` interpolation (1.0 = f60, 2.0 = f120).

I've [done an attempt](https://github.com/Larpon/AnimeEffects/tree/experiment/show-current-frame-in-time-cursor) to set it in the cursor in the timeline, but it's not a very good solution so far.
image

Does anyone have any ideas of were we could put it in the UI?

I've also thought about a dedicated [info widget](https://github.com/Larpon/AnimeEffects/tree/feature/info-widget) or an info bar somewhere.

It'd be nice with some input on this.

### PR DESCRIPTION
**Pull request by larpon**
This should eventually close #7 

@herace if/when people agree on pulling this in - it's my intention to squash the commit.

It unfortunately ended up touching quite a few places in the codebase because from what I can see, there's no infrastructure to signal _application_ setting changes. And to accommodate the addition of several timeline formats (as suggested by @Jose-Moreno), which can be expanded upon I had to add a General setting for this. I also had to add a `TimeFormat` class which is intended to encapsulate the formatting of the different timeline formats. 

If you have better ideas for more logic names for all the additions (classes, signals, etc.) please let me know.

... So please give your feedback on both the settings dialog (Menu -> Option -> General settings... -> Time Scale Format) and the functionality it provides:
image
image
image

I hope you like the idea in general!
It's my intention to add more useful info/functionality to the `InfoLabelWidget`later. An example could be a zoom control or similar functionality.

Right now the `InfoLabelWidget` itself can be hidden (on a per session basis) by dragging the bottom edge of the the above timeline widget down (this is an unintentional sideeffect of how QtWidgets works - but I somewhat like it :) ).

### CODE REVIEW

**Comment by larpon** [comment]
Maybe the "Timeline Scale format" should simply be "Timeline Format"?

**Comment by larpon** [comment]
Hmm... InfoLabelWidget should also probably be renamed to TimelineInfoWidget to adhere to the existing file naming scheme

**Comment by herace** [comment]
Hey @Larpon great stuff, going to to QA test the timeline and see how it feels. :ok_hand: 

I think "Timeline Format" is simple and straight to the point. Also i do agree "InfoLabelWidget" should be renamed to "TimelineInfoWidget" its way more descriptive the the original.

After QA testing could probably provided some good feedback on the timeline and whats the next steps will be

**Comment by herace** [comment]
Okay im back @Larpon, so ive been fiddling around for quite sometime and i think im ready to give back some feedback.

Unexpectedly  i ended up not sticking to any of the timeline format at all whatsoever, instead i constantly switching format when animating which i found it <b>extremely useful</b> , switching from TimeBase to FPS.

In result i get perfect animation timing using the time based format and for smoother looking animation frame by frame i switch to fps. 
 Personally I honestly never experience this kind of workflow, usually i just stick to FPS. But the constant switching time formats is very nice. I think i need to do a small project to properly give you more additional feedback but overall its definitely and improvement.

I think the next steps for the Timeline panel is to relocate the playback buttons (maybe at the bottom like in the screenshot).  

ae_timeline_ss_1

Also maybe a dropdown box to change the time format but dont worry about that its is just my personal preference.

OH also not related, but i think the middle mouse buttons should be enabled by default.

**Comment by larpon** [comment]
@herace - awesome!

Hmm... I've actually never thought about, being able to quickly switch between time formats would be useful...

Maybe we should consider shortcuts for switching between them? ... or as you suggest: a dropdown to switch between them. (I'll present the idea to the guys on IRC/Discord also). 

We just have to make sure it doesn't impact e.g. exporting. I think currently only FPS has an impact - but I'm not 100% sure. 

Beside that I'm not even sure FPS is even a user facing setting? I think @hidefuku might have been planning on supporting different fps around the code base - but some places it's still hard coded to 60fps? (It was in the timeline code I've fiddled with).

I fully agree on the playback controls - they should be pretty easy to move as they reside in the same parent widget - will you make an issue? - that way we can remember all the good ideas :)
Maybe even add some (GitHub) labels? (If you give me access to modifying them on the repo I'll be happy to try and maintain and apply them)

**Pull request merged**
